### ISSUE TITLE
Angular 6.1.9 - Error

### ISSUE THREAD

**Issue by aiwha-dev** [Genex/ng2-mmbreakpoints#2]
I'm using:
```
"@angular/core": "^6.1.9",
"ng2-mmbreakpoints": "^0.6.2",
"rxjs": "^6.3.3",
"rxjs-compat": "^6.3.3",
```

And i get the following error.

> TypeError: Observable_1.Observable.fromEventPattern is not a function
>     at new MatchmediaService (index.ts?07db:63)

we used to be at these versions and all was fine.
```
"@angular/core": "^5.0.2",
"ng2-mmbreakpoints": "^0.6.2",
"rxjs": "^5.5.2",
(no compat)
```

Any suggestions?

**Comment by mattirwin** [comment]
Yeah, the issue is with rxjs compat actually, I think some of the method calls used in the module got messed up with 6.3.x though I’ve yet to confirm this directly. I do know that another user of this module in Angular 6 had the same issue you are discribing and fixed it by forcing use of rxjs compat version 6.2.2.  That’s what I would recommend for now.

An updated version of this module that is compatible with rxjs 6 / Angular 6 is currently in the works to address this more permanently. Look for it in the next few weeks. I’ll leave this issue open until its posted.

**Comment by aiwha-dev** [comment]
Thank you! dowgrading rxjs to 6.2.2 indeed fixes it and is compatible with the current angular version.

**Comment by mattirwin** [comment]
Took longer than I expected to get back to this, but I pushed a 1.0.0 version that fixes this issue.  Further, it *should* eliminate the need to use rxjs compat in general.
